name: CI-SFTP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  volcar-proyecto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME}}
          host: ${{ secrets.SERVER_IP}}
          port: 22 # default is 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: ${{ secrets.SERVER_PATH}}
          
  recompilar-server:
    runs-on: ubuntu-latest
    needs: volcar-proyecto

    steps:
      - name: Conexión al server x2
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ejecutar recompilador
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME}}@${{ secrets.SERVER_IP }}  "source /home/ubuntu/.nvm/nvm.sh && /home/ubuntu/.nvm/versions/node/v16.15.1/bin/pm2 restart recompile"

