name: CI-SFTP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SERVER_USERNAME}}
          server: ${{ secrets.SERVER_IP}}
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: ${{ secrets.SERVER_PATH}}
          
          # sftp args
          args: '-o ConnectTimeout=5'
          
  execute-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Conexión al server x2
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ejecutar recompilador
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME}}@${{ secrets.SERVER_IP }}  "source /home/ubuntu/.nvm/nvm.sh && /home/ubuntu/.nvm/versions/node/v16.15.1/bin/pm2 restart recompile"

